# Generated by Django 6.0.4 on 2026-04-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supportdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_pattern', models.CharField(max_length=255, unique=True)),
                ('answer_template', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('complexity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='supportdesk.ticket')),
            ],
        ),
    ]
